#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts /tmp/hosts
sed -i 's/127.0.0.1\(\s*\)localhost/127.0.0.2\1localhost/' /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cp /tmp/hosts /etc/hosts
