#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /etc/hosts
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
